archive/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('board/', include('board.urls'))
]

board/urls.py
from django.urls import path
from . import views

app_name = 'board'

urlpatterns = [
    path('create/', views.create, name='create'),
    path('', views.index, name='index'),
    path('<int:question_pk>/', views.detail, name='detail'),
    path('<int:question_pk>/update/', views.update, name='update'),
    path('<int:question_pk>/delete/', views.delete, name='delete'),
] 

board/models.py
from django.db import models

CATEGORY_CHOICES = [
    ('python', '파이썬'),
    ('web', '웹'),
    ('django', '장고'),
]

class Question(models.Model):
    title = models.CharField(max_length=100)
    category = models.CharField(max_length=100, choices=CATEGORY_CHOICES)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

board/forms.py
from django import forms
from .models import Question

class QuestionForm(forms.ModelForm):

    class Meta:
        model = Question
        fields = '__all__'

board/views.py
from django.core.paginator import Paginator
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_safe, require_POST, require_http_methods
from .models import Question
from .forms import QuestionForm

@require_http_methods(['GET', 'POST'])
def create(request):
    if request.method == 'POST':
        form = QuestionForm(request.POST)
        if form.is_valid():
            question = form.save()  
            return redirect('board:detail', question.pk)
    else:
        form = QuestionForm()

    context = {'form': form}
    return render(request, 'board/form.html', context)


@require_http_methods(['GET', 'SAFE'])
def index(request):
    questions = Question.objects.order_by('-pk')

    paginator = Paginator(questions, 2)

    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    context = {'page_obj': page_obj,}
    return render(request, 'board/index.html', context)


@require_safe
def detail(request, question_pk):
    question = get_object_or_404(Question, pk=question_pk)
    context = {'question': question,}
    return render(request, 'board/detail.html', context)


@require_http_methods(['GET', 'POST'])
def update(request, question_pk):
    question = get_object_or_404(Question, pk=question_pk)
    
    if request.method == 'POST':
        form = QuestionForm(request.POST, instance=question)
        if form.is_valid():
            question = form.save()              
            return redirect('board:detail', question.pk)
    else:
        form = QuestionForm(instance=question)
    
    context = {
        'question': question,
        'form': form,
    }
    return render(request, 'board/form.html', context)


@require_POST
def delete(request, question_pk):
    question = get_object_or_404(Question, pk=question_pk)
    question.delete()
    return redirect('board:index')

board/templates/board/detail.html
{% extends 'base.html' %}

{% block content %}
<h1>{{ question.title }}</h1>
<strong>
  {{ question.created_at }} | {{ question.updated_at }}
</strong>

<h2>{{ question.get_category_display}}</h2>

<p>{{ question.content|linebreaksbr }}</p>

<div>
  <a href="{% url 'board:index' %}"><button>Back</button></a>
</div>

<div>
  <a href="{% url 'board:update' question.pk %}"><button>Edit</button></a>
</div>

<form action="{% url 'board:delete' question.pk %}" method="POST">
  {% csrf_token %}
  <button onclick="return confirm('삭제하시겠습니까?')">Delete</button>
</form>
{% endblock content %}

board/templates/board/form.html
{% extends 'base.html' %} {% block content %}

<form method="POST">
  {% csrf_token %}

  <!-- form 은 input 관련해서만 생성 -->
  {{ form.as_p }}

  <button>제출</button>
</form>

{% endblock content %}

board/templates/board/index.html
{% extends 'base.html' %} {% block content %}

<h1>INDEX</h1>

<ul>
  {% for question in page_obj %}
  <li>
    <a href="{% url 'board:detail' question.pk %}">{{ question.title }}</a>
  </li>
  {% endfor %}
</ul>

<div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ page_obj.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">next</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
</div>

{% endblock content %}

templates/base.html
{% load static %}
{% load static tailwind_tags %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Django</title>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    {% comment %} {% tailwind_css %} {% endcomment %}
  </head>
  <body>

  {% include 'navbar.html'%}

  {% block content %}
  {% endblock content %}

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
  </body>
</html>

templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'board:index' %}">Logo</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link" aria-current="page" href="{% url 'board:index' %}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'board:create' %}">Create</a>
        </li>
      </ul>
    </div>
  </div>
</nav>